repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"]
      - id: debug-statements
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args:
          - --jobs=8
